name: update-IPlist

on:
  schedule:
    - cron: '*/120 * * * *' # every 120 minutes
  workflow_dispatch: # on button click

jobs:

  process-IPlist:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download and compress the IPList
      run: |
        # 从 URL 下载文本内容
        $url = "https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/combine/all.txt"
        $content = Invoke-WebRequest -Uri $url -UseBasicParsing | Select-Object -ExpandProperty Content
        
        # 去除注释
        $cleanedContent = $content -replace "^#.*`n", ""
        
        # 写到文件
        Set-Content -Path "IP-List/BTN-IP-List-all.txt" -Value $cleanedContent -Force
        
        # 压缩文件
        Compress-Archive -Path "IP-List/BTN-IP-List-all.txt" -DestinationPath "IP-List/BTN-IP-List-all.zip" -Force
        
      shell: pwsh
      
    - name: Commit and Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Update IPlist"
        directory: .
