name: update-IPlist

on:
  schedule:
    - cron: '0 */2 * * *' # 每2小时执行一次
  workflow_dispatch: # 手动触发

jobs:
  process-IPlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 获取完整历史记录以便比较更改
      
    - name: Download with retry
      run: |
        mkdir -p IP-List
        max_retries=3
        retry_count=0
        
        until [ $retry_count -ge $max_retries ]
        do
          if curl -s "https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/combine/all.txt" -o IP-List/BTN-IP-List-all-raw.txt; then
            echo "Download successful"
            break
          else
            retry_count=$((retry_count+1))
            echo "Download failed. Retry attempt $retry_count of $max_retries in 10 seconds..."
            sleep 10
          fi
        done
        
        if [ $retry_count -eq $max_retries ]; then
          echo "Download failed after $max_retries attempts"
          exit 1
        fi
        
    - name: Process IP list
      run: |
        # 创建去除注释的版本
        grep -v '^#' IP-List/BTN-IP-List-all-raw.txt > IP-List/BTN-IP-List-all-clean.txt
        
        # 统计信息
        raw_count=$(wc -l < IP-List/BTN-IP-List-all-raw.txt)
        clean_count=$(wc -l < IP-List/BTN-IP-List-all-clean.txt)
        comment_count=$((raw_count - clean_count))
        echo "原始文件行数: $raw_count"
        echo "清理后行数: $clean_count"
        echo "注释行数: $comment_count"
        
        # 计算文件哈希值
        raw_hash=$(sha256sum IP-List/BTN-IP-List-all-raw.txt | cut -d' ' -f1)
        clean_hash=$(sha256sum IP-List/BTN-IP-List-all-clean.txt | cut -d' ' -f1)
        
        # 创建包含哈希值的README文件
        echo "# IP List Files" > IP-List/README.md
        echo "## Generated: $(date)" >> IP-List/README.md
        echo "### BTN-IP-List-all-raw.txt" >> IP-List/README.md
        echo "- SHA256: $raw_hash" >> IP-List/README.md
        echo "- Lines: $raw_count" >> IP-List/README.md
        echo "### BTN-IP-List-all-clean.txt" >> IP-List/README.md
        echo "- SHA256: $clean_hash" >> IP-List/README.md
        echo "- Lines: $clean_count" >> IP-List/README.md
        
    - name: Commit and Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Update IPlist - $(date +'%Y-%m-%d %H:%M') - Raw: $raw_count, Clean: $clean_count"
        directory: .