name: update-IPlist

on:
  schedule:
    - cron: '*/30 * * * *' # 每30分钟执行一次
  workflow_dispatch: # 手动触发

jobs:
  process-IPlist:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # 获取完整历史记录以便比较更改
      
    - name: Download with retry
      run: |
        mkdir -p IP-List
        max_retries=3
        retry_count=0
        
        until [ $retry_count -ge $max_retries ]
        do
          if curl -s "https://raw.githubusercontent.com/PBH-BTN/BTN-Collected-Rules/main/combine/all.txt" -o IP-List/BTN-IP-List-all-original.txt; then
            echo "Download successful"
            break
          else
            retry_count=$((retry_count+1))
            echo "Download failed. Retry attempt $retry_count of $max_retries in 10 seconds..."
            sleep 10
          fi
        done
        
        if [ $retry_count -eq $max_retries ]; then
          echo "Download failed after $max_retries attempts"
          exit 1
        fi
        
    - name: Process IP list and generate hashes
      id: process
      run: |
        # 创建去除注释的版本
        grep -v '^#' IP-List/BTN-IP-List-all-original.txt > IP-List/BTN-IP-List-all-simplified.txt
        
        # 统计信息
        raw_count=$(wc -l < IP-List/BTN-IP-List-all-original.txt)
        clean_count=$(wc -l < IP-List/BTN-IP-List-all-simplified.txt)
        comment_count=$((raw_count - clean_count))
        echo "原始文件行数: $raw_count"
        echo "清理后行数: $clean_count"
        echo "注释行数: $comment_count"
        
        
    - name: Commit and Push Changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        message: "Update IPlist"
        directory: .